#!/usr/bin/env python3
"""
weather_updater.py
──────────────────
Fetches current weather from Open-Meteo (free, no API key needed) and writes
a weather.txt file, then pushes it to a GitHub repo so VRChat can download it
via VRCStringDownloader.

Open-Meteo docs: https://open-meteo.com/en/docs
GitHub raw files are on VRChat's trusted URL list:
  https://raw.githubusercontent.com/YOUR_NAME/YOUR_REPO/main/weather.txt

Setup:
  pip install requests PyGithub
  Set the four constants below, then run on a schedule (cron, GitHub Actions, etc.)

  The simplest free option is a GitHub Actions workflow that runs this script
  every 10 minutes and commits the result back to the same repo.
  See the included weather_updater.yml for a ready-made workflow.
"""

import sys
import json
import datetime
import requests
from github import Github  # pip install PyGithub

# ── Config ────────────────────────────────────────────────────────────────────

LATITUDE  = 45.7597  # Lyon, France
LONGITUDE = 4.8422

# GitHub personal access token with repo write permission
# Set this as a secret in GitHub Actions → available as os.environ["GH_TOKEN"]
import os
GITHUB_TOKEN  = os.environ.get("GH_TOKEN", "YOUR_TOKEN_HERE")
GITHUB_REPO   = "yourname/vrc-weather"   # e.g. "alice/vrc-world"
GITHUB_FILE   = "weather.txt"            # path inside the repo
GITHUB_BRANCH = "main"

# ── Weather state mapping ─────────────────────────────────────────────────────
# Open-Meteo WMO weather code → our shader state
# 0=clear  1=cloudy  2=rain  3=thunder
# Full WMO table: https://open-meteo.com/en/docs#weathervariables

def wmo_to_state(code: int) -> int:
    if code == 0:                          return 0  # Clear sky
    if code in (1, 2, 3):                  return 1  # Partly/mostly cloudy
    if code in (45, 48):                   return 1  # Fog (treat as cloudy)
    if code in (51, 53, 55):               return 2  # Drizzle
    if code in (61, 63, 65):               return 2  # Rain
    if code in (71, 73, 75, 77):           return 2  # Snow (rain state)
    if code in (80, 81, 82):               return 2  # Rain showers
    if code in (85, 86):                   return 2  # Snow showers
    if code in (95, 96, 99):               return 3  # Thunderstorm
    return 1  # fallback: cloudy

# ── Fetch from Open-Meteo ─────────────────────────────────────────────────────

def fetch_weather() -> dict:
    url = (
        "https://api.open-meteo.com/v1/forecast"
        f"?latitude={LATITUDE}&longitude={LONGITUDE}"
        "&current=weathercode,cloudcover,windspeed_10m"
        "&windspeed_unit=percent"   # returns 0-100 scale relative to Beaufort 12
        "&timezone=auto"
    )

    # windspeed_unit=percent isn't a real Open-Meteo param;
    # we normalise km/h ourselves (Beaufort 12 ≈ 118 km/h)
    url = (
        "https://api.open-meteo.com/v1/forecast"
        f"?latitude={LATITUDE}&longitude={LONGITUDE}"
        "&current=weathercode,cloudcover,windspeed_10m"
        "&timezone=auto"
    )

    resp = requests.get(url, timeout=10)
    resp.raise_for_status()
    data = resp.json()["current"]

    wmo          = int(data["weathercode"])
    cloud_pct    = float(data["cloudcover"])           # 0-100
    wind_kmh     = float(data["windspeed_10m"])        # km/h
    wind_pct     = min(wind_kmh / 118.0 * 100.0, 100) # normalise to 0-100%

    return {
        "weather_state":   wmo_to_state(wmo),
        "cloud_coverage":  round(cloud_pct, 1),
        "wind_speed":      round(wind_pct, 1),
        "description":     f"WMO {wmo}",
        "updated_utc":     datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M"),
    }

# ── Write weather.txt ─────────────────────────────────────────────────────────

def build_text(w: dict) -> str:
    lines = [
        f"# Auto-generated by weather_updater.py — {w['updated_utc']} UTC",
        f"weather_state:{w['weather_state']}",
        f"cloud_coverage:{w['cloud_coverage']}",
        f"wind_speed:{w['wind_speed']}",
        f"description:{w['description']}",
    ]
    return "\n".join(lines) + "\n"

# ── Push to GitHub ────────────────────────────────────────────────────────────

def push_to_github(content: str):
    gh   = Github(GITHUB_TOKEN)
    repo = gh.get_repo(GITHUB_REPO)

    try:
        existing = repo.get_contents(GITHUB_FILE, ref=GITHUB_BRANCH)
        repo.update_file(
            path    = GITHUB_FILE,
            message = "chore: update weather data",
            content = content,
            sha     = existing.sha,
            branch  = GITHUB_BRANCH,
        )
        print(f"[weather_updater] Updated {GITHUB_FILE} in {GITHUB_REPO}")
    except Exception:
        repo.create_file(
            path    = GITHUB_FILE,
            message = "chore: create weather data",
            content = content,
            branch  = GITHUB_BRANCH,
        )
        print(f"[weather_updater] Created {GITHUB_FILE} in {GITHUB_REPO}")

# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    try:
        weather = fetch_weather()
        text    = build_text(weather)
        print(text)
        push_to_github(text)
    except Exception as e:
        print(f"[weather_updater] ERROR: {e}", file=sys.stderr)
        sys.exit(1)
